"""add field year to Car model

Revision ID: 9c2c949763d8
Revises: f73a68de2f97
Create Date: 2019-12-24 16:37:42.378784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2c949763d8'
down_revision = 'f73a68de2f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('year', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_car_year'), 'car', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_year'), table_name='car')
    op.drop_column('car', 'year')
    # ### end Alembic commands ###
