"""add Car model, add CarLanguage association tab

Revision ID: f73a68de2f97
Revises: 63d2f5db026d
Create Date: 2019-12-24 10:36:26.347038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73a68de2f97'
down_revision = '63d2f5db026d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_language',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=124), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('car_id', 'language_id')
    )
    op.create_index(op.f('ix_car_language_name'), 'car_language', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_language_name'), table_name='car_language')
    op.drop_table('car_language')
    op.drop_table('car')
    # ### end Alembic commands ###
